const mongoose = require('mongoose');

const ApplicantSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    opportunityId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Opportunity',
      required: true,
      index: true,
    },
    // Match score percentage (0 - 100) calculated by AI background queue workers
    matchScore: {
      type: Number,
      default: null,
      min: 0,
      max: 100,
    },
    // Snapshot of applicant's skill/talent vector at the time of application
    applicantVector: {
      type: [Number],
      default: [],
    },
    // Flag to track whether background queue workers have completed the match calculation
    matchScoreCalculated: {
      type: Boolean,
      default: false,
      index: true,
    },
    // Detailed AI score breakdown / reasoning generated by queue workers
    matchDetails: {
      vectorSimilarity: { type: Number, default: 0 },
      skillMatchScore: { type: Number, default: 0 },
      reasoning: { type: String, default: '' },
    },
    // Application status tracking
    status: {
      type: String,
      enum: ['applied', 'under_review', 'shortlisted', 'interviewing', 'offered', 'rejected', 'withdrawn'],
      default: 'applied',
      index: true,
    },
    // Snapshot of the resume used at the time of application
    resumeUrl: {
      type: String,
      default: '',
    },
    // Admin / Employer notes & feedback
    adminNotes: {
      type: String,
      default: '',
    },
    appliedAt: {
      type: Date,
      default: Date.now,
    },
  },
  {
    timestamps: true,
  }
);

// Compound unique index to prevent a user from applying to the same opportunity multiple times
ApplicantSchema.index({ userId: 1, opportunityId: 1 }, { unique: true });

module.exports = mongoose.model('Applicant', ApplicantSchema);
